import { Customer, CustomerTier, DiscountRule, ProductCategory, Product, UpsellRule, User, Warehouse, WarehouseStock, Quotation, Subscription } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user_admin',
    name: 'Alexander Admin',
    email: 'admin@dealflow360.com',
    role: 'ADMIN',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'user_sales_rep',
    name: 'Alex Rivera',
    email: 'alex.sales@dealflow360.com',
    role: 'SALES_REP',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'user_sales_manager',
    name: 'Sarah Jenkins',
    email: 'sarah.manager@dealflow360.com',
    role: 'SALES_MANAGER',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'user_finance',
    name: 'Frank Miller',
    email: 'frank.finance@dealflow360.com',
    role: 'FINANCE',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'user_customer_acme',
    name: 'John Vance (Acme Corp)',
    email: 'john.customer@acme.com',
    role: 'CUSTOMER',
    customerId: 'cust_acme',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const SEED_CUSTOMER_TIERS: CustomerTier[] = [
  {
    id: 'tier_bronze',
    name: 'Bronze',
    baseDiscountLimitPct: 5,
    priorityLevel: 1,
    paymentTermsDays: 15,
  },
  {
    id: 'tier_silver',
    name: 'Silver',
    baseDiscountLimitPct: 10,
    priorityLevel: 2,
    paymentTermsDays: 30,
  },
  {
    id: 'tier_gold',
    name: 'Gold',
    baseDiscountLimitPct: 15,
    priorityLevel: 3,
    paymentTermsDays: 45,
  },
  {
    id: 'tier_enterprise',
    name: 'Enterprise',
    baseDiscountLimitPct: 25,
    priorityLevel: 4,
    paymentTermsDays: 60,
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust_acme',
    name: 'Acme Corporation',
    tierId: 'tier_gold',
    salesRepId: 'user_sales_rep',
    contactEmail: 'purchasing@acme.com',
    contactPhone: '+1-555-0199',
    address: '100 Innovation Way, Chicago, IL 60601',
    creditLimit: 150000,
    creditStatus: 'GOOD',
    riskProfile: 'LOW',
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'cust_technova',
    name: 'TechNova Ltd',
    tierId: 'tier_silver',
    salesRepId: 'user_sales_rep',
    contactEmail: 'procurement@technova.io',
    contactPhone: '+1-555-0244',
    address: '45 Silicon Blvd, Austin, TX 78701',
    creditLimit: 75000,
    creditStatus: 'GOOD',
    riskProfile: 'MEDIUM',
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'cust_global',
    name: 'Global Retail Corp',
    tierId: 'tier_enterprise',
    salesRepId: 'user_sales_rep',
    contactEmail: 'deals@globalretail.com',
    contactPhone: '+1-555-0811',
    address: '770 Broadway, New York, NY 10003',
    creditLimit: 500000,
    creditStatus: 'GOOD',
    riskProfile: 'LOW',
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-01-20T00:00:00.000Z',
  },
];

export const SEED_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat_hardware',
    name: 'Hardware',
    description: 'Physical computers, peripherals and enterprise devices',
    maxCategoryDiscountPct: 15,
  },
  {
    id: 'cat_software',
    name: 'Software & Cloud',
    description: 'SaaS platforms, cloud storage and annual licenses',
    maxCategoryDiscountPct: 25,
  },
  {
    id: 'cat_services',
    name: 'Professional Services',
    description: 'Deployment, onboarding and technical consultation',
    maxCategoryDiscountPct: 10,
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_laptop_pro',
    sku: 'LP-100',
    name: 'Laptop Pro 16" Enterprise',
    categoryId: 'cat_hardware',
    basePrice: 1499,
    unitCost: 950,
    isSubscription: false,
    stockTrackable: true,
    status: 'ACTIVE',
    description: 'High-performance 16-inch corporate workstation with hardware TPM encryption.',
  },
  {
    id: 'prod_ent_support',
    sku: 'SUP-247',
    name: 'Enterprise 24/7 SLA Support',
    categoryId: 'cat_software',
    basePrice: 499,
    unitCost: 120,
    isSubscription: true,
    subscriptionInterval: 'MONTHLY',
    stockTrackable: false,
    status: 'ACTIVE',
    description: '15-minute response time, dedicated enterprise account engineer, and uptime SLA guarantee.',
  },
  {
    id: 'prod_cloud_backup',
    sku: 'CB-001',
    name: 'DealFlow Cloud Backup Pro',
    categoryId: 'cat_software',
    basePrice: 199,
    unitCost: 40,
    isSubscription: true,
    subscriptionInterval: 'MONTHLY',
    stockTrackable: false,
    status: 'ACTIVE',
    description: 'Encrypted multi-region automated backup with instant snapshot rollback.',
  },
  {
    id: 'prod_install_service',
    sku: 'SRV-INST',
    name: 'Onsite Deployment & Setup',
    categoryId: 'cat_services',
    basePrice: 750,
    unitCost: 300,
    isSubscription: false,
    stockTrackable: false,
    status: 'ACTIVE',
    description: 'Certified engineer on-site setup, network configuration, and system imaging.',
  },
  {
    id: 'prod_ext_warranty',
    sku: 'WRN-3YR',
    name: '3-Year Complete Care Warranty',
    categoryId: 'cat_hardware',
    basePrice: 299,
    unitCost: 50,
    isSubscription: false,
    stockTrackable: false,
    status: 'ACTIVE',
    description: 'Comprehensive accidental damage and next-business-day onsite hardware replacement.',
  },
];

export const SEED_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh_main',
    code: 'WH-MAIN',
    name: 'Main Distribution Center',
    location: 'Chicago, IL',
    priority: 1,
  },
  {
    id: 'wh_east',
    code: 'WH-EAST',
    name: 'East Coast Logistics Hub',
    location: 'Newark, NJ',
    priority: 2,
  },
];

export const SEED_WAREHOUSE_STOCK: WarehouseStock[] = [
  {
    id: 'stock_lp_main',
    warehouseId: 'wh_main',
    productId: 'prod_laptop_pro',
    totalQuantity: 8,
    reservedQuantity: 0,
    availableQuantity: 8,
  },
  {
    id: 'stock_lp_east',
    warehouseId: 'wh_east',
    productId: 'prod_laptop_pro',
    totalQuantity: 4,
    reservedQuantity: 0,
    availableQuantity: 4,
  },
];

export const SEED_UPSELL_RULES: UpsellRule[] = [
  {
    id: 'rule_lp_warranty',
    triggerProductId: 'prod_laptop_pro',
    recommendedProductId: 'prod_ext_warranty',
    ruleType: 'ADDON',
    discountIncentivePct: 10,
    reason: 'Protect enterprise hardware investment with next-business-day replacement.',
  },
  {
    id: 'rule_lp_support',
    triggerProductId: 'prod_laptop_pro',
    recommendedProductId: 'prod_ent_support',
    ruleType: 'CROSS_SELL',
    discountIncentivePct: 5,
    reason: 'Add dedicated 24/7 technical support for business fleets.',
  },
  {
    id: 'rule_lp_install',
    triggerProductId: 'prod_laptop_pro',
    recommendedProductId: 'prod_install_service',
    ruleType: 'ADDON',
    discountIncentivePct: 0,
    reason: 'Ensure zero-downtime employee onboarding with turnkey onsite setup.',
  },
];

export const SEED_DISCOUNT_RULES: DiscountRule[] = [
  {
    id: 'disc_rule_gold',
    tierId: 'tier_gold',
    maxDiscountPct: 15,
    requiresManagerApproval: true,
    requiresFinanceApproval: false,
  },
  {
    id: 'disc_rule_silver',
    tierId: 'tier_silver',
    maxDiscountPct: 10,
    requiresManagerApproval: true,
    requiresFinanceApproval: false,
  },
];

export const SEED_QUOTATIONS: Quotation[] = [
  {
    id: 'quot_1001',
    quotationNumber: 'QT-2026-1001',
    customerId: 'cust_acme',
    customerName: 'Acme Corporation',
    salesRepId: 'user_sales_rep',
    salesRepName: 'Alex Rivera',
    status: 'APPROVED',
    lines: [
      {
        id: 'line_1001_1',
        quotationId: 'quot_1001',
        productId: 'prod_laptop_pro',
        productName: 'Laptop Pro 16" Enterprise',
        quantity: 5,
        unitPrice: 1499,
        unitCost: 950,
        discountPct: 10,
        discountAmount: 749.5,
        taxRate: 8.5,
        taxAmount: 573.37,
        lineTotal: 7318.87,
        lineMarginPct: 29.58,
      },
      {
        id: 'line_1001_2',
        quotationId: 'quot_1001',
        productId: 'prod_ext_warranty',
        productName: '3-Year Complete Care Warranty',
        quantity: 5,
        unitPrice: 299,
        unitCost: 50,
        discountPct: 10,
        discountAmount: 149.5,
        taxRate: 8.5,
        taxAmount: 114.37,
        lineTotal: 1459.87,
        lineMarginPct: 81.42,
      },
    ],
    subtotal: 8990,
    discountAmount: 899,
    taxAmount: 687.74,
    total: 8778.74,
    totalCost: 5000,
    marginPct: 38.2,
    riskScore: 18,
    riskLevel: 'LOW',
    approvalRequired: false,
    approvalStatus: 'NOT_REQUIRED',
    validityDate: '2026-10-31T23:59:59.000Z',
    notes: 'Q4 standard refresh bundle.',
    createdAt: '2026-09-01T14:30:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
];
